/**
 * Root layout: fonts, site metadata, and the chrome every page shares.
 *
 * ── IN SIMPLE WORDS ──
 * Header on top, page in the middle, footer at the bottom — defined once here
 * instead of being wrapped around each page by hand.
 *
 * ── WHY IT'S BUILT THIS WAY (change at your peril) ──
 * Poppins is loaded through next/font rather than the @font-face block the old
 * project kept in fonts.css. next/font self-hosts the files, emits the CSS with
 * the page, and reserves the metrics up front — so the headline does not reflow
 * once the font lands. The raw @font-face version fetched the .ttf only after
 * CSS parsing and shifted the layout on every cold load.
 *
 * `--font-sans` is the variable shadcn's own components read, so pointing
 * Poppins at it is what makes every primitive inherit the brand typeface
 * without a font class on any of them.
 *
 * ── DO NOT ──
 * - Do not move <Toaster /> into a page. Toasts are fired from the footer form
 *   on every route, and a per-page mount would unmount mid-transition and drop
 *   the message the user was meant to read.
 * - Do not add "use client" here. This file is what lets the pages stay server
 *   components; the two interactive pieces (SiteHeader, ContactForm) opt in on
 *   their own.
 */
import type { Metadata } from "next";
import { Open_Sans, Poppins } from "next/font/google";

import { SiteHeader } from "@/components/layout/site-header";
import { SiteFooter } from "@/components/layout/site-footer";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";

/**
 * Two families, split by ROLE — Poppins sets headings, Open Sans sets body.
 *
 * Poppins is geometric: every letter is built from near-perfect circles, which
 * is exactly what gives a headline its presence and exactly what makes it tiring
 * at 16px for a paragraph — the round `o a e` shapes are hard to tell apart at
 * small sizes, so the eye slows down. Open Sans is humanist: it carries the
 * asymmetric, pen-drawn detail that keeps letterforms distinct at body size.
 *
 * Weights are role-scoped, and the scoping is checked rather than assumed.
 * Poppins ships 500 and 600 only: 600 is every h1/h2/h3 and the wordmark, 500
 * is shadcn's CardTitle/SheetTitle. 400 went with the body role and 700 is
 * used by nothing — grep `font-heading` before adding a weight back.
 *
 * Open Sans is a VARIABLE font, so its 400/500/600 are one file, not three.
 * That asymmetry is why the weight list matters for Poppins and does not for
 * Open Sans: each Poppins weight is a separate download.
 */
const poppins = Poppins({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["500", "600"],
  display: "swap",
});

const openSans = Open_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: "swap",
});

/**
 * One sentence, three tags: the meta description, og:description and
 * twitter:description. It was written out three times, and every copy still
 * carried the old filler after the hero had been rewritten — which is exactly
 * how a stale claim survives an edit. Declared once so the search snippet and
 * the share card cannot disagree.
 *
 * This is the sentence Google prints under the result and the one that sits
 * beneath every pasted link, so it claims only what the testimonials say:
 * shipped on time, and reachable while it happens.
 */
const SITE_DESCRIPTION =
  "We ship scalable software on time, and stay reachable while we do it.";

export const metadata: Metadata = {
  metadataBase: new URL("https://arcompsol.com"),
  title: {
    default: "Arcompsol",
    template: "%s | Arcompsol",
  },
  description: SITE_DESCRIPTION,
  icons: {
    icon: [
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
    ],
    apple: "/apple-touch-icon.png",
  },
  manifest: "/site.webmanifest",

  // The og:image itself is generated by app/opengraph-image.tsx rather than
  // listed here, so the card is drawn from the real logo, font and client
  // list at build time. X falls back to og:image, so `twitter` sets only the
  // card type. Do not re-add an `images` array to either block: two sources
  // for one tag is how a stale share card survives a redesign.
  //
  // Without these, every share of this site — Slack, WhatsApp, LinkedIn, a DM —
  // renders as a bare URL with no title, no summary and no image. For a company
  // whose enquiries arrive by someone forwarding the link, that is the first
  // impression, and it was missing entirely.
  openGraph: {
    type: "website",
    siteName: "Arcompsol",
    locale: "en_US",
    url: "https://arcompsol.com",
    title: "Arcompsol",
    description: SITE_DESCRIPTION,
  },
  twitter: {
    card: "summary_large_image",
    title: "Arcompsol",
    description: SITE_DESCRIPTION,
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      // globals.css sets `scroll-behavior: smooth` on html, which Next cannot
      // see from CSS. Without this attribute it assumes the default and lets a
      // route change animate the scroll back to the top — so clicking Careers
      // scrolls the whole old page past you before the new one appears. The
      // attribute tells Next to jump instantly on navigation while leaving
      // in-page anchor scrolling (the nav's #services and #contact-form tabs)
      // smooth, which is the only place smooth was ever wanted.
      data-scroll-behavior="smooth"
      className={`${poppins.variable} ${openSans.variable} h-full antialiased`}
    >
      <head>
        {/* Scroll-reveal starts elements hidden and JavaScript reveals them. If
            the bundle is blocked, fails, or is still loading, this is what stops
            the page rendering blank. It is the difference between a degraded
            experience and no experience. */}
        <noscript>
          <style>{`[data-reveal]{opacity:1 !important;transform:none !important}`}</style>
        </noscript>
      </head>
      <body className="flex min-h-full flex-col">
        {/* Skip link. Every page opens with the same header, so a keyboard or
            screen-reader user otherwise tabs through the wordmark and five nav
            tabs before reaching any content — on every single navigation. It is
            visually hidden until focused, which is the point: it costs sighted
            users nothing and is the first stop for everyone else. */}
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-100 focus:rounded-lg focus:bg-brand focus:px-4 focus:py-2 focus:font-medium focus:text-white"
        >
          Skip to content
        </a>
        <SiteHeader />
        {/* scroll-mt-20: the skip link jumps here, and a keyboard user landing
            with the top of main tucked under the sticky header is the exact
            failure the skip link exists to prevent. */}
        <main id="main" className="flex-1 scroll-mt-20">
          {children}
        </main>
        <SiteFooter />
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
